# Generated by Django 3.0.3 on 2020-04-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('province', models.CharField(max_length=120)),
                ('country', models.CharField(default='Viet Nam', max_length=120)),
                ('postcode', models.CharField(max_length=120)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='billing.BillingProfile')),
            ],
        ),
    ]
